/**
 * Legal screen — Privacy Policy & Terms of Service
 * Placeholder text for pre-launch; replace with real legal copy before release.
 */

import { Pressable, ScrollView, StyleSheet, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { router, useLocalSearchParams } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
import Animated, { FadeInDown } from 'react-native-reanimated';
import { ThemedText } from '@/components/ui/ThemedText';
import { useTheme } from '@/hooks/useTheme';
import { BorderRadius, Colors, Spacing } from '@/constants/theme';

type LegalSection = 'privacy' | 'terms';

const CONTENT: Record<LegalSection, { title: string; icon: string; sections: { heading: string; body: string }[] }> = {
  privacy: {
    title: 'Privacy Policy',
    icon: 'shield-checkmark-outline',
    sections: [
      {
        heading: 'Information We Collect',
        body: 'NutriSnap collects information you provide during account creation (name, email via Google sign-in), health-related data you enter (weight, height, age, dietary goals), food scan images, and nutrition logs. We also collect anonymous usage analytics to improve the app experience.',
      },
      {
        heading: 'How We Use Your Data',
        body: 'Your data is used to provide personalized nutrition tracking, generate AI-powered food analysis, calculate calorie and macro goals, and track your progress over time. We do not sell your personal data to third parties.',
      },
      {
        heading: 'Data Storage & Security',
        body: 'Your data is stored securely on Supabase (PostgreSQL) with row-level security policies. Food scan images are stored on Cloudinary with secure upload presets. All data transmission uses HTTPS encryption.',
      },
      {
        heading: 'Data Retention & Deletion',
        body: 'You can export all your data at any time from the Profile screen. You can also permanently delete your account and all associated data. Deletion is irreversible and removes all meals, hydration logs, weight history, and profile information.',
      },
      {
        heading: 'Third-Party Services',
        body: 'NutriSnap uses the following third-party services: Google Sign-In (authentication), Google Gemini (AI food analysis), Supabase (database and auth), Cloudinary (image hosting), and Expo (app framework and notifications).',
      },
      {
        heading: 'Contact',
        body: 'For privacy-related questions, please reach out through the Feedback section in the app or contact us at support@nutrisnap.app.',
      },
    ],
  },
  terms: {
    title: 'Terms of Service',
    icon: 'document-text-outline',
    sections: [
      {
        heading: 'Acceptance of Terms',
        body: 'By using NutriSnap, you agree to these Terms of Service. If you do not agree, please discontinue use of the app.',
      },
      {
        heading: 'Service Description',
        body: 'NutriSnap is a nutrition tracking app that uses AI-powered food scanning to estimate nutritional content. All nutritional data provided by the AI is an estimate and should not be used as a substitute for professional dietary advice.',
      },
      {
        heading: 'Health Disclaimer',
        body: 'NutriSnap is not a medical device and does not provide medical advice. The calorie and macro estimates are approximations generated by AI and may not be 100% accurate. Always consult a healthcare professional before making significant changes to your diet.',
      },
      {
        heading: 'User Responsibilities',
        body: 'You are responsible for maintaining the security of your account. You agree not to misuse the service, attempt to reverse-engineer the AI models, or use the app for any purpose that violates applicable laws.',
      },
      {
        heading: 'Intellectual Property',
        body: 'NutriSnap and its original content, features, and functionality are owned by the NutriSnap team. The app is protected by copyright, trademark, and other laws.',
      },
      {
        heading: 'Limitation of Liability',
        body: 'NutriSnap is provided "as is" without warranties of any kind. We are not liable for any health outcomes resulting from the use of nutritional estimates provided by the app.',
      },
      {
        heading: 'Changes to Terms',
        body: 'We reserve the right to modify these terms at any time. Continued use of the app constitutes acceptance of any changes. We will notify users of significant changes through the app.',
      },
    ],
  },
};

export default function LegalScreen() {
  const { theme } = useTheme();
  const params = useLocalSearchParams<{ section?: string }>();
  const section: LegalSection = (params.section as LegalSection) || 'privacy';
  const content = CONTENT[section];

  return (
    <SafeAreaView style={[styles.container, { backgroundColor: theme.background }]}>
      {/* Top bar */}
      <View style={styles.topBar}>
        <Pressable style={styles.backButton} onPress={() => router.back()}>
          <Ionicons name="chevron-back" size={22} color={Colors.brown} />
        </Pressable>
        <ThemedText variant="bodySemiBold">{content.title}</ThemedText>
        <View style={styles.backButton} />
      </View>

      <ScrollView
        showsVerticalScrollIndicator={false}
        contentContainerStyle={styles.scrollContent}
      >
        {/* Header icon */}
        <Animated.View entering={FadeInDown.delay(80).springify()} style={styles.headerIcon}>
          <Ionicons
            name={content.icon as any}
            size={36}
            color={Colors.olive}
          />
        </Animated.View>

        <Animated.View entering={FadeInDown.delay(100).springify()}>
          <ThemedText variant="label" color={Colors.muted} align="center" style={styles.lastUpdated}>
            Last updated: June 2026
          </ThemedText>
        </Animated.View>

        {/* Content sections */}
        {content.sections.map((s, idx) => (
          <Animated.View
            key={s.heading}
            entering={FadeInDown.delay(140 + idx * 60).springify()}
            style={styles.sectionCard}
          >
            <ThemedText variant="h3" style={styles.sectionHeading}>
              {s.heading}
            </ThemedText>
            <ThemedText variant="body" color={Colors.brownMid} style={styles.sectionBody}>
              {s.body}
            </ThemedText>
          </Animated.View>
        ))}

        <View style={styles.bottomPadding} />
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1 },
  topBar: {
    paddingHorizontal: Spacing.xl,
    paddingTop: Spacing.sm,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  backButton: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.white,
  },
  scrollContent: {
    paddingHorizontal: Spacing.xl,
    paddingTop: Spacing.xl,
  },
  headerIcon: {
    alignItems: 'center',
    marginBottom: Spacing.md,
  },
  lastUpdated: {
    marginBottom: Spacing.xl,
  },
  sectionCard: {
    backgroundColor: Colors.white,
    borderRadius: BorderRadius.lg,
    borderWidth: 1,
    borderColor: Colors.border,
    padding: Spacing.lg,
    marginBottom: Spacing.md,
    gap: Spacing.sm,
  },
  sectionHeading: {
    fontSize: 16,
  },
  sectionBody: {
    lineHeight: 22,
  },
  bottomPadding: { height: 80 },
});
