/**
 * Legal screen — Privacy Policy & Terms of Service.
 * Keep this in sync with the hosted copy at docs/privacy-policy.html (the URL
 * submitted to the Play Console).
 */

import { Pressable, ScrollView, StyleSheet, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { router, useLocalSearchParams } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
import Animated, { FadeInDown } from 'react-native-reanimated';
import { ThemedText } from '@/components/ui/ThemedText';
import { useTheme } from '@/hooks/useTheme';
import { BorderRadius, Colors, Spacing } from '@/constants/theme';

type LegalSection = 'privacy' | 'terms';

const CONTENT: Record<LegalSection, { title: string; icon: string; sections: { heading: string; body: string }[] }> = {
  privacy: {
    title: 'Privacy Policy',
    icon: 'shield-checkmark-outline',
    sections: [
      {
        heading: 'Information We Collect',
        body: 'Account information you provide via Google Sign-In (name, email). Health and wellness data you enter: height, weight, age, biological sex, dietary preferences, nutrition goals, and any self-reported medical conditions. Activity data: daily steps (read from Android Health Connect only if you grant permission), sleep, and hydration. Your food logs and the photos you take when scanning meals. We also collect anonymous usage analytics and crash diagnostics to improve reliability.',
      },
      {
        heading: 'How We Use Your Data',
        body: 'To provide personalized nutrition tracking, analyze food photos, calculate calorie and macro targets, and show your progress. If you use the optional Friends feature, other users you connect with can see only your streak and consistency score — never your meals, calories, weight, photos, or any other data. We do not sell your personal data to anyone.',
      },
      {
        heading: 'Health & Activity Data',
        body: 'If you connect Android Health Connect, we read your daily step count only — no other health records. You can revoke this at any time in Health Connect settings. Self-reported medical conditions are used solely to tailor guidance (for example, avoiding aggressive calorie deficits) and are never used diagnostically or shared.',
      },
      {
        heading: 'Data Storage & Security',
        body: 'Your data is stored on Supabase (PostgreSQL) protected by row-level security, so each account can access only its own data. Meal and profile photos are stored on Cloudinary. All transmission uses HTTPS. AI credentials are held server-side and never shipped in the app.',
      },
      {
        heading: 'Third-Party Services',
        body: 'Google Sign-In (authentication); Groq (AI food-photo analysis using a Meta Llama vision model — your scan photos are processed to estimate nutrition); Supabase (database, authentication, backend functions); Cloudinary (image hosting); Open Food Facts (a public food database queried by the name you type for manual entry); and Expo (app framework and notifications).',
      },
      {
        heading: 'Data Retention & Deletion',
        body: 'You can export all of your data at any time from the Profile screen. You can permanently delete your account from within the app — this irreversibly removes your login, profile, meals, hydration and weight history, activity data, and stored food photos. To request deletion by email, contact support@nyurix.app.',
      },
      {
        heading: "Children's Privacy",
        body: 'Nyurix is not directed to children under 13, and we do not knowingly collect data from them. If you believe a child has provided us data, contact us and we will delete it.',
      },
      {
        heading: 'Contact',
        body: 'For privacy questions or data requests, use the Feedback section in the app or email support@nyurix.app.',
      },
    ],
  },
  terms: {
    title: 'Terms of Service',
    icon: 'document-text-outline',
    sections: [
      {
        heading: 'Acceptance of Terms',
        body: 'By using Nyurix, you agree to these Terms of Service. If you do not agree, please discontinue use of the app.',
      },
      {
        heading: 'Service Description',
        body: 'Nyurix is a nutrition tracking app that uses AI-powered food scanning to estimate nutritional content. All nutritional data provided by the AI is an estimate and should not be used as a substitute for professional dietary advice.',
      },
      {
        heading: 'Health Disclaimer',
        body: 'Nyurix is not a medical device and does not provide medical advice. The calorie and macro estimates are approximations generated by AI and may not be 100% accurate. Always consult a healthcare professional before making significant changes to your diet.',
      },
      {
        heading: 'User Responsibilities',
        body: 'You are responsible for maintaining the security of your account. You agree not to misuse the service, attempt to reverse-engineer the AI models, or use the app for any purpose that violates applicable laws.',
      },
      {
        heading: 'Intellectual Property',
        body: 'Nyurix and its original content, features, and functionality are owned by the Nyurix team. The app is protected by copyright, trademark, and other laws.',
      },
      {
        heading: 'Limitation of Liability',
        body: 'Nyurix is provided "as is" without warranties of any kind. We are not liable for any health outcomes resulting from the use of nutritional estimates provided by the app.',
      },
      {
        heading: 'Changes to Terms',
        body: 'We reserve the right to modify these terms at any time. Continued use of the app constitutes acceptance of any changes. We will notify users of significant changes through the app.',
      },
    ],
  },
};

export default function LegalScreen() {
  const { theme } = useTheme();
  const params = useLocalSearchParams<{ section?: string }>();
  const section: LegalSection = (params.section as LegalSection) || 'privacy';
  const content = CONTENT[section];

  return (
    <SafeAreaView style={[styles.container, { backgroundColor: theme.background }]}>
      {/* Top bar */}
      <View style={styles.topBar}>
        <Pressable style={styles.backButton} onPress={() => router.back()}>
          <Ionicons name="chevron-back" size={22} color={Colors.brown} />
        </Pressable>
        <ThemedText variant="bodySemiBold">{content.title}</ThemedText>
        <View style={styles.backButton} />
      </View>

      <ScrollView
        showsVerticalScrollIndicator={false}
        contentContainerStyle={styles.scrollContent}
      >
        {/* Header icon */}
        <Animated.View entering={FadeInDown.delay(80).springify()} style={styles.headerIcon}>
          <Ionicons
            name={content.icon as any}
            size={36}
            color={Colors.olive}
          />
        </Animated.View>

        <Animated.View entering={FadeInDown.delay(100).springify()}>
          <ThemedText variant="label" color={Colors.muted} align="center" style={styles.lastUpdated}>
            Last updated: June 2026
          </ThemedText>
        </Animated.View>

        {/* Content sections */}
        {content.sections.map((s, idx) => (
          <Animated.View
            key={s.heading}
            entering={FadeInDown.delay(140 + idx * 60).springify()}
            style={styles.sectionCard}
          >
            <ThemedText variant="h3" style={styles.sectionHeading}>
              {s.heading}
            </ThemedText>
            <ThemedText variant="body" color={Colors.brownMid} style={styles.sectionBody}>
              {s.body}
            </ThemedText>
          </Animated.View>
        ))}

        <View style={styles.bottomPadding} />
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1 },
  topBar: {
    paddingHorizontal: Spacing.xl,
    paddingTop: Spacing.sm,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  backButton: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.white,
  },
  scrollContent: {
    paddingHorizontal: Spacing.xl,
    paddingTop: Spacing.xl,
  },
  headerIcon: {
    alignItems: 'center',
    marginBottom: Spacing.md,
  },
  lastUpdated: {
    marginBottom: Spacing.xl,
  },
  sectionCard: {
    backgroundColor: Colors.white,
    borderRadius: BorderRadius.lg,
    borderWidth: 1,
    borderColor: Colors.border,
    padding: Spacing.lg,
    marginBottom: Spacing.md,
    gap: Spacing.sm,
  },
  sectionHeading: {
    fontSize: 16,
  },
  sectionBody: {
    lineHeight: 22,
  },
  bottomPadding: { height: 80 },
});
